services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: obs_personal_p
      MYSQL_USER: cnicolas
      MYSQL_PASSWORD: Basketp3l
      MYSQL_ROOT_PASSWORD: Clemneosio
    ports:
      - '3306:3306'
